spring:
  application:
    name: api-gateway
  cloud:
    consul:
      host: discovery
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Auth
          uri: http://auth:8080
          predicates:
            - Path=/api/auth/**
        - id: Rooms
          uri: lb://rooms-service
          predicates:
            - Path=/api/rooms/**
        - id: Movies
          uri: lb://movies-service
          predicates:
            - Path=/api/movies/**
        - id: User-Collections
          uri: lb://user-collections-service
          predicates:
            - Path=/api/user-collections/**
#        - id: frontend
#          uri: http://frontend:8080
#          predicates:
#            - Path=/**